import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import SummaryData from '../components/Dashboard/SummaryData'
import Header from '../components/Header'
import SideBar from '../components/SideBar'

export default function Dashboard() {
  const router = useRouter()

  useEffect(() => {
    if (!localStorage.getItem("accessToken")) {
      router.push('/Login')
    }
  }, [])

  return (
    <div className=''>
      <Head>
        <title>Inventer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <SideBar />

      <main className='justify-center py-2 bg-gray-100'>
        <SummaryData/>
        <div className='flex justify-between ml-64'>
          <div className='p-5 bg-white rounded-lg '>
            <p className='mb-3 font-bold'> Top Selling products</p>

            <div class="w-20 h-28 bg-white rounded-lg shadow-md dark:bg-gray-800 dark:border-gray-700">

              <Image class="p-8 rounded-t-lg h" width={300} height={300} src="/assets/Product_sample_icon_picture.png" alt="product image" />
              <div class="px-5 pb-5">

                <p class=" font-semibold tracking-tight text-gray-900 dark:text-white"> Item</p>

              </div>
            </div>

          </div>
          {/* for the pi chart  */}
          <div className=''></div>

        </div>
        {/* for more visualization  */}
        <div className=''></div>
      </main>

    </div>
  )
}
