import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Header from '../components/Header'
import Search from '../components/search'
import SideBar from '../components/sideeBar'
import { getAuthToken } from '../utils/functions'

export default function User() {
  const usersData = async () => {
    const headers = getAuthToken()
    let response = await axios.get('http://localhost:8000/user/users', headers)
    setData(response.data.results)
  }
  const [data, setData] = useState([])
  useEffect(() => {
    data.length <= 0 && usersData()
  }, [data])
  let arr = [1, 2, 3, 4]

  const addUser = () => {
    console.log("from user page")
  }
  return (
    <div >
      <Head>
        <title>Inventer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SideBar />
      <main>
        <Search name=" Add User " func={addUser} />
      </main>
      <div class="overflow-x-auto relative shadow-md sm:rounded-lg UsersTable">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr class="bg-green-500">
              <th scope="col" class="p-4 ">
                <div class="flex items-center">
                </div>
              </th>
              <th scope="col" class="py-3 px-6">
                Email
              </th>
              <th scope="col" class="py-3 px-6">
                Name
              </th>
              <th scope="col" class="py-3 px-6">
                Role
              </th>
              <th scope="col" class="py-3 px-6">
                Action
              </th>
            </tr>
          </thead>
          <tbody>
            {data.map((ele) => {
              return (
                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                  <td class="p-4 w-4">
                    <div class="flex items-center">

                    </div>
                  </td>
                  <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {ele.email}
                  </th>
                  <td class="py-4 px-6">
                    {ele.fullname}
                  </td>
                  <td class="py-4 px-6">
                    {ele.role}
                  </td>
                  <td class="flex items-center py-4 px-6 space-x-3">
                    <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                    <a href="#" class="font-medium text-red-600 dark:text-red-500 hover:underline">Remove</a>
                  </td>
                </tr>
              )
            })}

          </tbody>
        </table>
      </div>


    </div>
  )
}