import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Header from '../components/Header'
import SideBar from '../components/SideBar'
import { getAuthToken } from '../utils/functions'

export default function UserActivity() {

  const usersData = async () => {
    const headers = getAuthToken()
    let response = await axios.get('https://inventer-ms.herokuapp.com/user/activities-log', headers)
    setData(response.data.results)

  }
  const [data, setData] = useState([])
  useEffect(() => {
    data.length <= 0 && usersData()
  }, [data])

  const [query, setQuery] = useState("")
  console.log(query)

  return (
    <div >


      <Head>
        <title>Inventer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SideBar />
      <main>

        <div class="overflow-x-auto relative  sm:rounded-lg UsersTable">
          <table class="w-11/12 text-sm text-left text-gray-500 dark:text-gray-400 mt-20 border-collapse border"  >
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
              <tr class="bg-green-500">
                <th scope="col" class="p-4 rounded-l-lg ">
                  <div class="flex items-center">
                  </div>
                </th>
                <th scope="col" class="py-3 px-6 text-white">
                  Action
                </th>
                <th scope="col" class="py-3 px-6 text-white">
                  Preformed By
                </th>
                <th scope="col" class="py-3 px-6 text-white rounded-r-lg">
                  Created At
                </th>
              </tr>
            </thead>
            <tbody>
              {data.map((ele) => {

                if (ele.email.toLowerCase().includes(query)) {
                  return (
                    <tr key={ele.id} class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                      <td class="p-4 w-4">
                        <div class="flex items-center">

                        </div>
                      </td>
                      <th scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {ele.action}
                      </th>
                      <td class="py-4 px-6">
                        {ele.fullname}
                      </td>
                      <td class="py-4 px-6">
                        {ele.created_at}
                      </td>
                    </tr>
                  )
                }
              })}

            </tbody>
          </table>

        </div>

       
      </main>
    </div >
  )
}